@startuml Oppgave 2
!theme plain
skinparam backgroundColor #FEFEFE
skinparam classBackgroundColor #F0F0F0
skinparam classBorderColor #333333

' * ENTITETER
' Bestillinger
entity "**Kunde**" as kunde {
    **kundenummer : INT {PK}**
    --
    navn : VARCHAR1
    adresse : VARCHAR
}

entity "**Ordre**" as ordre {
    **ordrenummer : INT {PK}**
    --
    ' Kunde.kundenummer* : INT {FK}
    ordredato : VARCHAR
    antatt_leveringsdato : VARCHAR
    reell_leveringsdato : VARCHAR
    rabatt : FLOAT
    betalingsstatus : VARCHAR
}

entity "**Stolmodell**" as stolmodell {
    **modell : VARCHAR {PK}**
    --
    modellnavn : VARCHAR
    stoltype : VARCHAR
    er_standard : BOOLEAN
}

entity "**Ordrelinje**" as ordrelinje {
    **id : INT {PK}**
    --
    ' Ordre.ordrenummer* : INT {FK}
    ' Stolmodell.modell* : VARCHAR {FK}
    antall : INT
    ' Stolmodell.er_standard* : BOOLEAN {FK}
}



' Lager
entity "**Standardmodell_lager**" as standardmodell_lager {
    **Stolmodell.modell* : INT {PK, FK}**
    --
    pris : FLOAT
    beholdning : INT
}

entity "**Deltype_lager**" as deltype_lager {
    **Deltype.delnummer* : INT {PK, FK}**
    --
    antall : INT
}



' Produksjon
entity "**Arbeidsstasjon**" as arbeidsstasjon {
    **nummer : INT {PK}**
    --
    plassering : VARCHAR
}

entity "**Deltype**" as deltype {
    **delnummer : INT {PK}**
    --
    navn : VARCHAR
    farge : VARCHAR
    pris : FLOAT
    beskrivelse : VARCHAR
    stoffbehov_meter : FLOAT
    er_stoff : BOOLEAN
    ' Arbeidsstasjon.nummer* : INT {FK}
}

entity "**Spesialmodell_del**" as spesialmodell_del {
    **Stolmodell.modell* : VARCHAR {PK, FK}**
    **Deltype.delnummer* : INT {PK, FK}**
    --
    antall_per_stol : INT
}

entity "**Stoffrull**" as stoffrull {
    **Deltype.delnummer* : INT {PK, FK}**
    **rullnummer : INT {PK}**
    --
    meter_igjen : FLOAT
}

entity "**Ordrelinje_stoffrull**" as ordrelinje_stoffrull {
    **Ordrelinje.id* : INT {PK, FK}**
    --
    ' Stoffrull.rullnummer* : INT {FK}
    meter_reservert : FLOAT
}

' * RELASJONER
kunde "    0..*\n \n▲\ntilhører " -down- "1..1" ordre : "\n legger\n▼"
ordre "         1..*\n \n▲\ninneholder " -down- "1..1" ordrelinje : "\n består av\n▼"
ordrelinje "          1..1\n \n▲\nrefererer til " -left- "1..1" stolmodell : "\n gjelder for\n▼"
stolmodell "         0..*\n \n▲\nkan være " -down- "0..1" standardmodell_lager : "\n har\n▼"
deltype_lager "         1..*\n \n▲\nrefererer til " -down- "1..1" deltype : "\n gjelder for\n▼"
deltype "         0..*\n \n▲\nkan produseres ved " -down- "1..1" arbeidsstasjon : "\n produseres ved\n▼"
stolmodell "         1..1\n \n▲\nrefererer til " -down- "1..1" spesialmodell_del : "\n gjelder for\n▼"
spesialmodell_del "         1..1\n \n▲\nrefererer til " -down- "1..1" deltype : "\n gjelder for\n▼"
deltype "         0..*\n \n▲\nkan være " -up- "0..1" stoffrull : "\n har\n▼"
stoffrull "         0..*\n \n▲\nkan være " -up- "0..1" ordrelinje_stoffrull : "\n kan være\n▼"
ordrelinje "         0..*\n \n▲\nkan ha " -down- "0..1" ordrelinje_stoffrull : "\n har\n▼"


@enduml